<div class="form-group<?php 
  if ($error) { echo ' has-error'; } 
  elseif ($_isPost && $value) { echo ' has-success'; }
  if ($_showFeedback) { echo ' has-feedback'; }
?>">
  <label class="control-label<?php if ($this->hideLabels) { echo ' sr-only'; } ?>" for="<?php echo $id?>"><?php echo $label ?></label>
  <?php if (@$addonPre || @$addonPost) { ?>
    <div class="input-group">
    <?php if (@$addonPre) { ?><div class="input-group-addon"><?php echo $addonPre;?></div><?php } ?>
  <?php } ?>
  <input id="<?php echo $id?>" name="<?php echo $name?>" type="<?php echo $type?>" 
         class="form-control" value="<?php echo $value?>" <?php 
    if ( ($error || $_isPost) && $this->showFeedback) { echo "aria-describedby='helpBlock$id' "; }
    if (@$placeholder) { echo "placeholder='$placeholder' "; }
    if (is_array(@$otherAttributes)) {
      foreach($otherAttributes as $k=>$v) {
        if (is_numeric($k)) {
            echo "$v ";
        } else {
            echo "$k='$v' ";            
        }
        
      }
    }
    ?>/>
    <?php if (@$addonPost) {?><div class="input-group-addon"><?php echo $addonPost; ?></div><?php } ?>
  <?php if (@$addonPre || @$addonPost) { ?></div><?php } ?>

    <?php if (@$error) { ?>
      <?php if ($_showFeedback) { ?><span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span><?php } ?>
      <p class="help-block"<?php if ($this->showFeedback) { echo " id='helpBlock$id'"; } ?>><?php echo $error ?></p>
    <?php } elseif ($_isPost && $_showFeedback && $value) { ?>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
    <?php } ?>
</div>