<div class="form-group<?php 
  if ($error) { echo ' has-error'; } 
  elseif ($_isPost) { echo ' has-success'; }
  if ($this->showFeedback) { echo ' has-feedback'; }
?>">
  <label class="control-label<?php if ($this->hideLabels && !@$multiple) { echo ' sr-only'; } ?>" for="<?php echo $id?>"><?php echo $label ?></label>
  <select id="<?php echo $id?>" name="<?php echo $name?>" class="form-control" <?php
    if (@$multiple) echo ' multiple';
    if ($size) echo " size='$size'"; 
     
    if ( ($error || $_isPost) && $this->showFeedback) { echo "aria-describedby='helpBlock$id' "; }
    if (is_array(@$otherAttributes)) {
      foreach($otherAttributes as $k=>$v) {
        echo "$k='$v' ";
      }
    }
    ?>><?php foreach($options as $k=>$v) { 
      $val = is_int($k) ? $v : $k;
      ?>
      <option value="<?php echo $val?>"<?php if ($val==$value) { echo ' SELECTED'; } ?>><?php echo $v?></option>
    <?php } ?></select>
    <?php if (@$error) { ?>
      <p class="help-block"<?php if ($this->showFeedback) { echo " id='helpBlock$id'"; } ?>><?php echo $error ?></p>
    <?php } else if (@$help) {?>
      <p class="help-block"><?php echo $help ?></p>
    <?php } ?>
</div>