<div class="form-group<?php 
          if ($error) { echo ' has-error'; } 
          elseif ($_isPost) { echo ' has-success'; }
          if ($this->showFeedback) { echo ' has-feedback'; }?>">
    <?php if (@$label) { ?>
    <label class="control-label <?php echo $this->horizontalLabelClass; ?>"><b><?php echo $label; ?></b></label>
    <div class="<?php echo $this->horizontalInputClass; ?>">
    <?php } else {?>
    <div class="<?php echo $this->horizontalInputClass; ?> col-sm-offset-2">
    <?php }?>
        <div class="checkbox<?php
          if (@$inline) { echo ' checkbox-inline'; } ?>
        ?>" id="<?php echo $id ?>">
            
            <?php 
            $inputs = Array();
            if (empty($id)) $id = uniqid('radio_');
            
            foreach($options as $k=>$opt) {
                
                if (is_numeric($k)) {
                    $opt_value = $key = $opt;
                    
                } else {
                    $opt_value = $key = $k;
                }
                
                $key = $this->makeKey($key);
                
                $html = '<label><input type="checkbox" id="' . $key . '"';
                
                if (empty($name)) $name = $id;
                $html .= "name='{$name}[]'";
                if ($value && in_array($opt_value, $value)) { $html .= ' checked'; }
                $html .= ' value="' . $opt_value . '"';
                
                $html .= ' /> ' . $opt . '</label>';
                
                $inputs[] = $html; 
            
            }
            echo join('<br />', $inputs);
            ?>
        </div>
    </div>
    <?php if ($error) {?>
        <div class="<?php echo $this->horizontalHelpClass; ?>">
            <div class="help-block">
                <?php echo $error; ?>
            </div>
        </div>
    <?php } else if (@$help) { ?>
        <div class="<?php echo $this->horizontalHelpClass; ?>">
            <div class="help-block">
                <?php echo $help; ?>
            </div>
        </div>
    <?php } ?>

    
</div>